### ISSUE TITLE
create new build MIX 4

### ISSUE THREAD

**Issue by ketanpatel25** [Inkypen79/kernel_xiaomi_odin#1]
i try to create new build to getting some error 

============================================
[ 98% 394/398] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_bu
ild")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soon
g/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list 
--available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.b
p
error: device/xiaomi/odin/Android.bp:1:1: module "soong_namespace": namespace hardware/xiaomi does not exist
19:05:41 soong bootstrap failed with: exit status 1

#### failed to build some targets (03:06 (mm:ss)) ####

please help me

**Comment by Inkypen79** [comment]
This isn't a kernel problem lol
To fix the error you need to clone this repository in hardware/xiaomi
https://github.com/LineageOS/android_hardware_xiaomi

**Comment by ketanpatel25** [comment]
Thank you @lnkypen79
